const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");

test("班表浮動工具列使用整合式左側操作列", () => {
  const html = read("src/renderer/index.html");
  const toolbarIndex = html.indexOf('class="toolbar-card toolbar-floating-card"');
  const controlStackIndex = html.indexOf('class="toolbar-control-stack"', toolbarIndex);
  const collapseIndex = html.indexOf('id="toolbarCollapseToggle"', toolbarIndex);
  const undoIndex = html.indexOf('id="scheduleUndoButton"', toolbarIndex);
  const redoIndex = html.indexOf('id="scheduleRedoButton"', toolbarIndex);
  const gridIndex = html.indexOf('id="toolbarGrid"', toolbarIndex);
  assert.ok(toolbarIndex >= 0 && controlStackIndex > toolbarIndex && collapseIndex > controlStackIndex && undoIndex > collapseIndex && redoIndex > undoIndex && gridIndex > redoIndex);
  assert.equal(html.includes('class="toolbar-top-row"'), false);
  const filterIndex = html.indexOf('id="tableDeptScopeFilter"');
  const topUndoIndex = html.indexOf('id="scheduleUndoTopButton"');
  const topRedoIndex = html.indexOf('id="scheduleRedoTopButton"');
  assert.ok(filterIndex >= 0 && topUndoIndex > filterIndex && topRedoIndex > topUndoIndex);
  assert.match(html, /class="toolbar-history-actions schedule-nav-history-actions"/);
  assert.match(html, /toolbar-section-overtime" hidden/);
  assert.match(html, /id="tablePrevWeekButton"[^>]* hidden/);
  assert.match(html, /id="tableNextWeekButton"[^>]* hidden/);
});

test("班表週捲動與例假排班顯示具有正式程式契約", () => {
  const actions = read("src/renderer/renderer-export-actions.js");
  const events = read("src/renderer/renderer-events-toolbar.js");
  const table = read("src/renderer/renderer-schedule-table.js");
  const cells = read("src/renderer/renderer-schedule-cells.js");
  const css = read("src/renderer/css/pages.css");
  const interaction = read("src/renderer/renderer-schedule-interaction.js");
  assert.match(actions, /const SCHEDULE_WEEK_SCROLL_DAYS = 7;/);
  assert.match(actions, /function canScrollScheduleByWeeks\(weeks\)/);
  assert.match(actions, /function scrollScheduleByWeeks\(weeks\)/);
  assert.match(actions, /maxScrollLeft: Math\.max\(0, tableWrap\.scrollWidth - tableWrap\.clientWidth\)/);
  assert.match(actions, /button\.disabled = !canScrollScheduleByWeeks\(weeks\)/);
  assert.match(events, /bindClick\("prevWeekButton", \(\) => scrollScheduleByWeeks\(-1\)\)/);
  assert.match(events, /bindClick\("nextWeekButton", \(\) => scrollScheduleByWeeks\(1\)\)/);
  assert.doesNotMatch(table, /regularHolidayWorkClass|regular-holiday-work-cell/);
  assert.match(cells, /function isRegularHolidayWorkSlot\(slot\)/);
  assert.doesNotMatch(cells, /renderRegularHolidayWorkIndicator|regular-holiday-work-indicator/);
  assert.match(cells, /renderShiftViewCell\(members, dateString\)/);
  assert.match(cells, /regular-holiday-work-seg/);
  assert.match(cells, /regular-holiday-work-member/);
  assert.match(css, /\.table-week-jump \{[\s\S]*?display: none !important;/);
  assert.match(css, /\.calendar-nav-left \.schedule-nav-history-actions \{[\s\S]*?display: inline-flex;/);
  assert.match(interaction, /function getScheduleUndoButtons\(\)/);
  assert.match(interaction, /scheduleUndoTopButton/);
  assert.match(interaction, /scheduleRedoTopButton/);
  assert.match(css, /\.table-sticky-cell-day\.sun:not\(\.today\)/);
  assert.match(css, /\.toolbar-floating-card \{[\s\S]*?grid-template-columns: auto minmax\(0, 1fr\) !important;/);
  assert.match(css, /\.toolbar-control-stack \{[\s\S]*?flex-direction: column;/);
  assert.match(css, /\.toolbar-floating-card > \.toolbar-grid \{[\s\S]*?display: block !important;/);
  assert.match(css, /\.toolbar-category-group \{[\s\S]*?flex-direction: column;/);
  assert.match(css, /\.toolbar-floating-card\.toolbar-floating-card-collapsed \{[\s\S]*?grid-template-columns: auto !important;/);
  assert.doesNotMatch(css, /\.cell\.regular-holiday-work-cell/);
  assert.doesNotMatch(css, /regular-holiday-work-indicator/);
  assert.match(css, /\.seg\.regular-holiday-work-seg \{\s*background: #ffe58f !important;\s*\}/);
  assert.match(css, /\.shift-view-member\.regular-holiday-work-member \{\s*background: #ffe58f;\s*\}/);
});
